Main svc
ekumrk/explore-with-me pull request #2
Opened 2024-11-15 18:27 UTC by ekumrk

2024-11-16 07:12 UTC, VadimZharkov commented on statistics-service/http-client/pom.xml
Свойства с версиями и кодировками будут для всех модулей одинаковые, поэтому лучше вынести в самый корневой родительский pom.

2024-11-16 07:20 UTC, VadimZharkov reviewed
dto-service не удачное название, т.к. данный модуль не является полноценным сервисом, это просто библиотека с набором классов

2024-11-16 07:23 UTC, VadimZharkov commented on statistics-service/dto-service/src/main/java/ru/practicum/exception/ErrorHandler.java
Т.к. данный модуль не является приложением, то и хэндлер здесь лишний. Хэндлер логично разместить в приложении, т.е. в модуле где есть вызов SpringApplication.run();

2024-11-16 07:28 UTC, VadimZharkov commented on statistics-service/statistics-server/src/main/java/ru/practicum/StatisticsController.java
>      public InputEventDto saveEventStats(@RequestBody InputEventDto dto) {
На поля InputEventDto нужно навесить аннотации, а здесь добавить валидацию @RequestBody @Valid InputEventDto

2024-11-16 07:33 UTC, VadimZharkov commented on statistics-service/statistics-server/src/main/java/ru/practicum/repository/StatisticsRepository.java
>      @Query(" SELECT new ru.practicum.dto.OutputStatsDto(s.app, s.uri, COUNT(DISTINCT s.ip)) " +
Удобней пользоваться текстовыми блоками """ some multiline text """

2024-11-16 07:38 UTC, VadimZharkov commented on statistics-service/statistics-server/src/main/resources/schema.sql
>      ip varchar,
Лучше единообразно для всех ключ. слов использовать большие буквы

2024-11-16 07:41 UTC, VadimZharkov commented on statistics-service/statistics-server/src/main/resources/schema.sql
Нужно на колонки добавить ограничения на NULL

2024-11-16 07:44 UTC, VadimZharkov commented on event-service/src/main/java/ru/practicum/category/repository/CategoryRepository.java
> +@Repository
Можно не помечать `@Repository`, данная аннотация уже есть на базовом типе JpaRepository

2024-11-16 07:56 UTC, VadimZharkov commented on event-service/src/main/java/ru/practicum/compilation/model/Compilation.java
> +    @ManyToMany
Лучше добавить (fetch = FetchType.LAZY), чтобы тянулось из базы только при обращении к геттеру

2024-11-16 07:58 UTC, VadimZharkov commented on event-service/src/main/java/ru/practicum/compilation/model/Compilation.java
> +    private Boolean pinned;
Лучше примитивный тип boolean, ситуации когда будет null вроде не просматривается.

2024-11-16 08:00 UTC, VadimZharkov commented on event-service/src/main/java/ru/practicum/compilation/model/dto/NewCompilationDto.java
> +    private Boolean pinned;
Здесь тоже предпрочел бы примитивный тип boolean

2024-11-16 08:04 UTC, VadimZharkov commented on event-service/src/main/resources/schema.sql
Нужно добавить ограничения колонок на NULL,  в репозиториях во многих местах не нужно будет писать конструкции вида OR ((?1) is NULL

2024-11-16 08:05 UTC, VadimZharkov commented on event-service/src/main/resources/schema.sql
> +    title varchar
Нужно соблюдать единую стилистику - ключ. слова большими буквами

2024-11-16 08:09 UTC, VadimZharkov commented on event-service/src/main/java/ru/practicum/request/service/RequestServiceImpl.java
> +        if (event.getInitiator().getId() == userId) {
Здесь может возникнуть NullPointerException, если event.getInitiator() вернет null
Поэтому лучше добавить доп. проверку на null

2024-11-16 08:11 UTC, VadimZharkov requested changes
В целом хорошая работа, можно улучшить

2024-11-17 12:43 UTC, ekumrk commented on statistics-service/statistics-server/src/main/java/ru/practicum/repository/StatisticsRepository.java
>      @Query(" SELECT new ru.practicum.dto.OutputStatsDto(s.app, s.uri, COUNT(DISTINCT s.ip)) " +
Вадим, а такой вопрос, текстовые блоки используются в Java IDE с поддержкой JDK 15+, а у меня же версия джавы 11, наверное идея будет ругаться на это же? Если я не прав, сори, туплю немного

2024-11-17 12:58 UTC, ekumrk commented
Вадим, привет, благодарю за такой подробный разбор и подробное ревью. Вроде как все поправил, единственное, не сделал эти текстовые блоки, там выше по ним оставил коммент, почитал про это, вообще достаточно интересный способ писать длинные куски кода, возьму на вооружение)

2024-11-18 05:54 UTC, VadimZharkov commented on statistics-service/statistics-server/src/main/java/ru/practicum/repository/StatisticsRepository.java
>      @Query(" SELECT new ru.practicum.dto.OutputStatsDto(s.app, s.uri, COUNT(DISTINCT s.ip)) " +
Да если версия джавы не поддерживает, то будет ругаться. Просто на курсе разрешили переходить на джаву до 21 версии включительно.
Из текстовых блоков удобно копипастить SQL для запуска и отладки отдельно от джавы.

2024-11-18 05:54 UTC, VadimZharkov approved these changes

2024-11-19 06:57 UTC, merged